Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -34,6 +34,10 @@ jobs:
           -U ${{ secrets.AZURE_SQL_USER }} \
           -P ${{ secrets.AZURE_SQL_PASSWORD }} \
           -i ./V1_SCHEMA.sql
+          else 
+          echo "Schema file not found!"
+          exit 1
+          fi
 
       - name: Run Seed
         run: |
@@ -43,3 +47,6 @@ jobs:
           -U ${{ secrets.AZURE_SQL_USER }} \
           -P ${{ secrets.AZURE_SQL_PASSWORD }} \
           -i ./V2_seed.sql
+          else 
+          echo "Schema file not found,skipping"
+          fi
